[package]
name = "steam-master-server-implementation"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
rand = "0.9.0"
r2d2 = "0.8.10"
r2d2_sqlite = { version = "0.27", features = ["bundled"] }
jiff = "0.2.5"
atoi = "2.0.0"
regex = "1.11.1"
